services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: logflow-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: logflow
      CLICKHOUSE_USER: logflow
      CLICKHOUSE_PASSWORD: logflow_password
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data: